name: Preview Deployment

on:
  pull_request:

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v20

      - name: Set up nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v1

      - name: Build
        run: |
          nix build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./result/public"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.event.pull_request.title }}
          alias: deploy-preview-${{ github.event.number }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
